-- Found while adding SQL allow/deny tests for
-- 20260904180000_connection_requests_invites_access_helper.sql: a fresh
-- local `supabase db reset` leaves `authenticated` without SELECT on
-- `connection_invites` (0058_skill_discovery_and_connections.sql enabled RLS
-- and added a correctly-scoped "Inviters can view their own invites" policy,
-- but no migration ever granted the table-level privilege), confirmed via
-- `information_schema.role_table_grants` against a fresh local reset:
-- authenticated has TRUNCATE/REFERENCES/TRIGGER on this table but not
-- SELECT/INSERT/UPDATE/DELETE.
--
-- Same root cause and same verdict as the connections/courses/skills-
-- dependents grant gaps already documented and fixed in
-- 20260904100000_grant_connections_select.sql,
-- 20260904111500_grant_courses_select.sql, and
-- 20260904121500_grant_skills_courses_experience_dependents_select.sql:
-- Staging's Postgres instance has an ambient default ACL (not captured in
-- any migration) that grants `authenticated` full table privileges on new
-- tables automatically, so this is not currently broken for real users on
-- Staging. The fix still matters for local dev and for
-- `stage_bootstrap_consolidated.sql`'s "bootstrap a brand-new Staging
-- project from empty" use case (CLAUDE.md #17), which would not inherit
-- Staging's undocumented default.
--
-- The RLS policies on connection_invites already scope visible rows to the
-- inviter (and, as of this transition, their linked accounts), so this
-- grant is safe regardless of environment.

grant select on public.connection_invites to authenticated;
